-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.


CREATE TABLE factResults
(
    fact_id integer NOT NULL,
    mic_id smallint NOT NULL,
    band_id integer NOT NULL,
    venue_id smallint NOT NULL,
    source_id smallint NOT NULL,
    result varchar(10) NOT NULL,
    result_numeric decimal(3,2) NOT NULL,
    PRIMARY KEY (fact_id)
);

CREATE TABLE dimMics
(
    mic_id smallint NOT NULL,
    manufacturer varchar(20) NOT NULL,
    model varchar(20) NOT NULL,
    type varchar(10) NOT NULL,
    PRIMARY KEY (mic_id)
);

CREATE TABLE dimBand
(
    band_id integer NOT NULL,
    band_name varchar(30) NOT NULL,
    num_members smallint NOT NULL,
    style varchar(10) NOT NULL,
    PRIMARY KEY (band_id)
);

CREATE TABLE dimVenue
(
    venue_id smallint NOT NULL,
    venue_name varchar(50) NOT NULL,
    size varchar(10) NOT NULL,
    reverberance_seconds decimal(3,2) NOT NULL,
    PRIMARY KEY (venue_id)
);

CREATE TABLE flakeMembers
(
    member_id integer NOT NULL,
    band_id integer NOT NULL,
    role varchar(20) NOT NULL,
    PRIMARY KEY (member_id)
);

CREATE TABLE dimSource
(
    source_id smallint NOT NULL,
    source_name varchar(20) NOT NULL,
    PRIMARY KEY (source_id)
);

CREATE TABLE flakeMicUsed
(
    mic_used_id integer NOT NULL,
    member_id integer NOT NULL,
    source_id smallint NOT NULL,
    mic_name varchar(20) NOT NULL,
    mic_id smallint NOT NULL,
    PRIMARY KEY (mic_used_id)
);

ALTER TABLE factResults
    ADD FOREIGN KEY (mic_id)
    REFERENCES dimMics (mic_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE factResults
    ADD FOREIGN KEY (source_id)
    REFERENCES dimSource (source_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE factResults
    ADD FOREIGN KEY (band_id)
    REFERENCES dimBand (band_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE factResults
    ADD FOREIGN KEY (venue_id)
    REFERENCES dimVenue (venue_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE flakeMembers
    ADD FOREIGN KEY (band_id)
    REFERENCES dimBand (band_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE flakeMicUsed
    ADD FOREIGN KEY (mic_id)
    REFERENCES dimMics (mic_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE flakeMicUsed
    ADD FOREIGN KEY (source_id)
    REFERENCES dimSource (source_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE flakeMicUsed
    ADD FOREIGN KEY (member_id)
    REFERENCES flakeMembers (member_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE;

